"""Initial schema — core tables per Section 15 of the architecture spec.

Revision ID: 0001
Revises:
Create Date: 2026-09-27

Hand-written (not autogenerated) to match database/models/core.py exactly, since this
environment has no live Postgres to autogenerate against. Re-verify with
`alembic check` / `alembic revision --autogenerate` once a DB is available, before
adding further migrations on top of this one.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _timestamps():
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    ]


def upgrade() -> None:
    op.create_table(
        "tenant",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        *_timestamps(),
    )

    op.create_table(
        "user",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("role", sa.String(50), nullable=False, server_default="sales_rep"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        *_timestamps(),
    )
    op.create_index("ix_user_tenant_id", "user", ["tenant_id"])
    op.create_index("ix_user_email", "user", ["email"])

    op.create_table(
        "campaign",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("script_id", sa.String(100), nullable=False),
        sa.Column("script_version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("status", sa.String(30), nullable=False, server_default="draft"),
        sa.Column("telephony_provider", sa.String(30), nullable=False),
        sa.Column("call_window_start", sa.String(5), nullable=False),
        sa.Column("call_window_end", sa.String(5), nullable=False),
        sa.Column("timezone", sa.String(50), nullable=False, server_default="Asia/Kolkata"),
        sa.Column("max_concurrent_calls", sa.Integer, nullable=False, server_default="3"),
        sa.Column("max_call_duration_seconds", sa.Integer, nullable=False, server_default="420"),
        sa.Column("config", postgresql.JSONB, nullable=False, server_default="{}"),
        *_timestamps(),
    )
    op.create_index("ix_campaign_tenant_id", "campaign", ["tenant_id"])

    op.create_table(
        "lead",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaign.id"), nullable=False),
        sa.Column("phone_e164", sa.String(20), nullable=False),
        sa.Column("raw_phone", sa.String(50), nullable=False),
        sa.Column("dedupe_key", sa.String(20), nullable=False),
        sa.Column("contact_name", sa.String(255), nullable=True),
        sa.Column("business_name", sa.String(255), nullable=True),
        sa.Column("extra", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending"),
        sa.Column("attempts_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("consent_flag", sa.Boolean, nullable=True),
        sa.Column("source_row", postgresql.JSONB, nullable=False, server_default="{}"),
        *_timestamps(),
        sa.UniqueConstraint("campaign_id", "dedupe_key", name="uq_lead_campaign_dedupe"),
    )
    op.create_index("ix_lead_tenant_id", "lead", ["tenant_id"])
    op.create_index("ix_lead_campaign_id", "lead", ["campaign_id"])
    op.create_index("ix_lead_phone_e164", "lead", ["phone_e164"])
    op.create_index("ix_lead_status", "lead", ["status"])

    op.create_table(
        "call_attempt",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaign.id"), nullable=False),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("lead.id"), nullable=False),
        sa.Column("attempt_number", sa.Integer, nullable=False, server_default="1"),
        sa.Column("provider", sa.String(30), nullable=False),
        sa.Column("provider_call_id", sa.String(255), nullable=True),
        sa.Column("status", sa.String(30), nullable=False, server_default="queued"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer, nullable=True),
        sa.Column("outcome", sa.String(50), nullable=True),
        sa.Column("error", sa.Text, nullable=True),
        *_timestamps(),
        sa.UniqueConstraint("campaign_id", "lead_id", "attempt_number", name="uq_call_attempt_idempotency"),
    )
    op.create_index("ix_call_attempt_campaign_id", "call_attempt", ["campaign_id"])
    op.create_index("ix_call_attempt_lead_id", "call_attempt", ["lead_id"])
    op.create_index("ix_call_attempt_status", "call_attempt", ["status"])
    op.create_index("ix_call_attempt_provider_call_id", "call_attempt", ["provider_call_id"])

    op.create_table(
        "conversation",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("call_attempt_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("call_attempt.id"), nullable=False),
        sa.Column("script_id", sa.String(100), nullable=False),
        sa.Column("script_version", sa.Integer, nullable=False),
        sa.Column("current_state", sa.String(50), nullable=False, server_default="INTRO"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_reason", sa.String(100), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_conversation_call_attempt_id", "conversation", ["call_attempt_id"])

    op.create_table(
        "turn",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversation.id"), nullable=False),
        sa.Column("turn_index", sa.Integer, nullable=False),
        sa.Column("speaker", sa.String(20), nullable=False),
        sa.Column("state", sa.String(50), nullable=False),
        sa.Column("intent", sa.String(100), nullable=True),
        sa.Column("raw_llm_output", postgresql.JSONB, nullable=True),
        *_timestamps(),
        sa.UniqueConstraint("conversation_id", "turn_index", name="uq_turn_index"),
    )
    op.create_index("ix_turn_conversation_id", "turn", ["conversation_id"])

    op.create_table(
        "transcript_segment",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversation.id"), nullable=False),
        sa.Column("turn_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("turn.id"), nullable=True),
        sa.Column("speaker", sa.String(20), nullable=False),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("start_ms", sa.Integer, nullable=True),
        sa.Column("end_ms", sa.Integer, nullable=True),
        sa.Column("is_final", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("stt_confidence", sa.Float, nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_transcript_segment_conversation_id", "transcript_segment", ["conversation_id"])
    op.create_index("ix_transcript_segment_turn_id", "transcript_segment", ["turn_id"])

    op.create_table(
        "qualification",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversation.id"), nullable=False),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("lead.id"), nullable=False),
        sa.Column("outcome", sa.String(50), nullable=False),
        sa.Column("qualified", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0"),
        sa.Column("dimensions", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("facts", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("objections", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("evidence", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("next_action", sa.String(255), nullable=True),
        sa.Column("script_version", sa.Integer, nullable=False),
        sa.Column("model_version", sa.String(100), nullable=True),
        sa.Column("sales_followup_required", sa.Boolean, nullable=False, server_default=sa.false()),
        *_timestamps(),
    )
    op.create_index("ix_qualification_conversation_id", "qualification", ["conversation_id"])
    op.create_index("ix_qualification_lead_id", "qualification", ["lead_id"])
    op.create_index("ix_qualification_outcome", "qualification", ["outcome"])

    op.create_table(
        "callback",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("lead.id"), nullable=False),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversation.id"), nullable=True),
        sa.Column("requested_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(50), nullable=False, server_default="Asia/Kolkata"),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending"),
        sa.Column("notes", sa.Text, nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_callback_lead_id", "callback", ["lead_id"])

    op.create_table(
        "suppression",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("phone_e164", sa.String(20), nullable=False),
        sa.Column("reason", sa.String(100), nullable=False),
        sa.Column("source", sa.String(100), nullable=False),
        *_timestamps(),
        sa.UniqueConstraint("tenant_id", "phone_e164", name="uq_suppression_tenant_phone"),
    )
    op.create_index("ix_suppression_tenant_id", "suppression", ["tenant_id"])
    op.create_index("ix_suppression_phone_e164", "suppression", ["phone_e164"])

    op.create_table(
        "agent_config",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("key", sa.String(100), nullable=False),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("value", postgresql.JSONB, nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        *_timestamps(),
        sa.UniqueConstraint("tenant_id", "key", "version", name="uq_agent_config_key_version"),
    )
    op.create_index("ix_agent_config_tenant_id", "agent_config", ["tenant_id"])

    op.create_table(
        "script_version",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("script_id", sa.String(100), nullable=False),
        sa.Column("version", sa.Integer, nullable=False),
        sa.Column("file_path", sa.String(500), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        *_timestamps(),
        sa.UniqueConstraint("script_id", "version", name="uq_script_id_version"),
    )
    op.create_index("ix_script_version_script_id", "script_version", ["script_id"])

    op.create_table(
        "model_version",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("provider", sa.String(30), nullable=False),
        sa.Column("model_name", sa.String(100), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        *_timestamps(),
    )

    op.create_table(
        "outbox_event",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("aggregate_type", sa.String(50), nullable=False),
        sa.Column("aggregate_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(100), nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_outbox_event_aggregate_id", "outbox_event", ["aggregate_id"])
    op.create_index("ix_outbox_event_processed_at", "outbox_event", ["processed_at"])

    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant.id"), nullable=True),
        sa.Column("actor", sa.String(255), nullable=False),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("resource_type", sa.String(50), nullable=False),
        sa.Column("resource_id", sa.String(255), nullable=False),
        sa.Column("event_metadata", postgresql.JSONB, nullable=False, server_default="{}"),
        *_timestamps(),
    )
    op.create_index("ix_audit_log_tenant_id", "audit_log", ["tenant_id"])

    op.create_table(
        "export_job",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenant.id"), nullable=False),
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("campaign.id"), nullable=True),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending"),
        sa.Column("file_path", sa.String(500), nullable=True),
        sa.Column("requested_by", sa.String(255), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_export_job_tenant_id", "export_job", ["tenant_id"])


def downgrade() -> None:
    op.drop_table("export_job")
    op.drop_table("audit_log")
    op.drop_table("outbox_event")
    op.drop_table("model_version")
    op.drop_table("script_version")
    op.drop_table("agent_config")
    op.drop_table("suppression")
    op.drop_table("callback")
    op.drop_table("qualification")
    op.drop_table("transcript_segment")
    op.drop_table("turn")
    op.drop_table("conversation")
    op.drop_table("call_attempt")
    op.drop_table("lead")
    op.drop_table("campaign")
    op.drop_table("user")
    op.drop_table("tenant")
